In [1]:
import pandas as pd
import numpy as np
import transformations as tf
import os
from pathlib import Path

[   INFO   ] MusicExtractorSVM: no classifier models were configured by default


In [ ]:
input_path = '/home/gpu3/visfma/embeds'
file_name = 'x_fmasmallx_ele_014869_wav2clip_identity_none.npy'
transformation = 'pitchshift'
track = file_name.split('_')[2]+'_'+file_name.split('_')[3]
dataset = file_name.split('_')[1]
model = file_name.split('_')[4]

params = ['id']
for param in tf.tf_dict_params[transformation]:
    params.append(str(param)[:5])
df = pd.DataFrame(
    columns=params,
    index=params
)

for i, param1 in enumerate(params):
    if param1 == 'id':
        f1 = f"x_{dataset}_{track}_{model}_identity_none.npy"
        f1 = os.path.join(input_path, f1)
    else:
        f1 = f"x_{dataset}_{track}_{model}_{transformation}_{str(param1)[:5].replace('.', 'p')}.npy"
        f1 = os.path.join(input_path, f1)
    a1 = np.load(f1, 'r')[0,:]
    a1 = a1 / np.linalg.norm(a1)
    for j in range(i, len(params)):
        param2 = params[j]
        if param2 == 'id':
            f2 = f"x_{dataset}_{track}_{model}_identity_none.npy"
            f2 = os.path.join(input_path, f2)
        else:
            f2 = f"x_{dataset}_{track}_{model}_{transformation}_{str(param2)[:5].replace('.', 'p')}.npy"
            f2 = os.path.join(input_path, f2)
        a2 = np.load(f2, 'r')[0,:]
        a2 = a2 / np.linalg.norm(a2)
        d = np.sqrt(np.sum((a2-a1)**2))
        df.iloc[i,j] = d
        df.iloc[j,i] = d

df.to_csv("dist_nd.csv", index=True)
df.head(len(params))

[-0.59833074 -0.4529478  -0.4766039 ]
6.287415
[-0.09516323 -0.07204039 -0.07580284]
[-0.27236035 -0.43460616 -0.18237096]
8.379351
[-0.03250375 -0.05186633 -0.02176433]
[-0.20798323 -0.26351446 -0.1737634 ]
6.8743625
[-0.03025491 -0.03833293 -0.02527702]
[-0.18409827 -0.12541538 -0.06248944]
7.4941654
[-0.02456555 -0.01673507 -0.00833841]
[-0.0423094   0.08876238 -0.06661448]
7.913234
[-0.00534666  0.01121695 -0.00841811]
[-0.366058    0.16328356 -0.0626893 ]
8.710954
[-0.04202272  0.01874463 -0.00719661]
[-0.4954679   0.20449716 -0.07728703]
8.802485
[-0.05628727  0.02323175 -0.00878014]
[-0.65301573  0.37491238  0.04018665]
10.782549
[-0.06056228  0.03477029  0.00372701]
[-0.6533079   0.43283966  0.08950032]
10.658139
[-0.06129662  0.04061118  0.00839737]
[-0.75914013  0.37249553  0.22919431]
11.1432295
[-0.06812569  0.03342797  0.02056803]
[-1.0450764   0.37352225  0.35071954]
12.872256
[-0.08118829  0.02901762  0.02724616]
[-0.99628     0.29703006  0.2019515 ]
12.287341
[-0.081081

,id,1,2,3,4,5,6,7,8,9,...,-4,-5,-6,-7,-8,-9,-10,-11,-12,-24
id,0.0,0.930853,0.943596,1.020779,1.03031,1.05443,1.076097,1.078275,1.053745,1.030651,...,1.064817,1.073723,1.111047,1.108818,1.115745,1.120493,1.134799,1.133116,1.127812,1.128814
1,0.930853,0.0,0.559568,0.819521,0.911556,1.094109,1.09728,1.07578,1.098726,1.111484,...,0.652196,0.657235,0.724989,0.759882,0.778398,0.74211,0.799103,0.806189,0.897383,1.275613
2,0.943596,0.559568,0.0,0.483916,0.58361,0.848706,0.868335,0.862383,0.905423,0.937889,...,0.788033,0.825014,0.869597,0.880439,0.852353,0.820852,0.854164,0.881287,0.909793,1.163913
3,1.020779,0.819521,0.483916,0.0,0.379713,0.522328,0.533169,0.593686,0.666107,0.699138,...,0.890139,0.940855,0.982621,0.973001,0.928773,0.921727,0.945193,0.979043,0.957981,1.141811
4,1.03031,0.911556,0.58361,0.379713,0.0,0.477596,0.546038,0.584007,0.632784,0.691836,...,1.024484,1.054614,1.092882,1.07048,1.034241,1.018999,1.045888,1.068474,1.05122,1.102805
5,1.05443,1.094109,0.848706,0.522328,0.477596,0.0,0.182236,0.322753,0.37852,0.405675,...,1.113809,1.152701,1.190953,1.166317,1.129097,1.146847,1.162341,1.194283,1.151924,1.147835
6,1.076097,1.09728,0.868335,0.533169,0.546038,0.182236,0.0,0.279657,0.336958,0.374158,...,1.108076,1.150009,1.191167,1.164423,1.127576,1.149141,1.165919,1.198647,1.156226,1.175414
7,1.078275,1.07578,0.862383,0.593686,0.584007,0.322753,0.279657,0.0,0.217537,0.290718,...,1.089139,1.1257,1.172989,1.146201,1.11368,1.136118,1.153787,1.192405,1.161502,1.135238
8,1.053745,1.098726,0.905423,0.666107,0.632784,0.37852,0.336958,0.217537,0.0,0.18698,...,1.121513,1.150645,1.195484,1.163799,1.133097,1.151561,1.172448,1.201296,1.172911,1.139695
9,1.030651,1.111484,0.937889,0.699138,0.691836,0.405675,0.374158,0.290718,0.18698,0.0,...,1.108953,1.14009,1.182107,1.151658,1.124721,1.146908,1.159944,1.191408,1.160693,1.138523
